import { describe, expect, it } from "bun:test";
import { existsSync, mkdirSync, writeFileSync, readFileSync } from "node:fs";
import { mkdtempSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { cleanupOwnedOnly } from "../src/cleanup";

function write(p: string, content = "x") {
  mkdirSync(join(p, ".."), { recursive: true });
  writeFileSync(p, content);
}

describe("owned-only cleanup", () => {
  it("removes stale claude skills when marker exists", async () => {
    const repoRoot = mkdtempSync(join(tmpdir(), "nexus-repo-"));

    const skillsRoot = join(repoRoot, ".claude", "skills");
    mkdirSync(skillsRoot, { recursive: true });
    write(join(skillsRoot, ".nexus-managed"), "generated by nexus\n");

    // stale skill dir
    write(join(skillsRoot, "old-skill", "SKILL.md"), "old");
    // desired skill dir
    write(join(skillsRoot, "new-skill", "SKILL.md"), "new");

    await cleanupOwnedOnly({
      repoRoot,
      desiredPaths: [join(skillsRoot, "new-skill", "SKILL.md"), join(skillsRoot, ".nexus-managed")],
    });

    expect(existsSync(join(skillsRoot, "old-skill"))).toBeFalse();
    expect(existsSync(join(skillsRoot, "new-skill"))).toBeTrue();
  });

  it("does not touch claude skills if marker absent", async () => {
    const repoRoot = mkdtempSync(join(tmpdir(), "nexus-repo-"));
    const skillsRoot = join(repoRoot, ".claude", "skills");
    mkdirSync(skillsRoot, { recursive: true });

    write(join(skillsRoot, "user-skill", "SKILL.md"), "keep");

    await cleanupOwnedOnly({ repoRoot, desiredPaths: [] });

    expect(existsSync(join(skillsRoot, "user-skill", "SKILL.md"))).toBeTrue();
    expect(readFileSync(join(skillsRoot, "user-skill", "SKILL.md"), "utf8")).toBe("keep");
  });
});
