import { describe, expect, it } from "bun:test";
import { mkdtempSync, readFileSync, existsSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { emitCodex } from "../src/emitters/codex";

describe("codex emitter", () => {
  it("writes .codex/config.toml with header marker", async () => {
    const repoRoot = mkdtempSync(join(tmpdir(), "nexus-repo-"));

    await emitCodex({
      repoRoot,
      configToml: "[mcp]\nenabled = true\n",
    });

    const outPath = join(repoRoot, ".codex", "config.toml");
    expect(existsSync(outPath)).toBeTrue();

    const raw = readFileSync(outPath, "utf8");
    expect(raw).toContain("generated by nexus");
    expect(raw).toContain("[mcp]");
  });
});
