import { describe, expect, it } from "bun:test";
import { mkdtempSync, readFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { loadLocalPack } from "../src/resolver/localPack";
import { loadPackMcpServers, loadPackOpenCodeAssets, packSkillByItemId } from "../src/resolver/coreItems";
import { emitClaude } from "../src/emitters/claude";
import { emitMcp } from "../src/emitters/mcp";
import { emitCodex } from "../src/emitters/codex";
import { emitOpenCode } from "../src/emitters/opencode";

const FIX = join(import.meta.dir, "..", "fixtures", "packs", "core");

describe("golden: core pack", () => {
  it("emits deterministic outputs", async () => {
    const repoRoot = mkdtempSync(join(tmpdir(), "replix-golden-"));

    const pack = await loadLocalPack(FIX);
    const skill = packSkillByItemId(pack, "repo-status");
    const mcp = await loadPackMcpServers(FIX);
    const assets = await loadPackOpenCodeAssets(FIX);

    await emitClaude({
      repoRoot,
      skills: [
        {
          id: "core:repo-status",
          itemId: skill.itemId,
          srcDir: skill.srcDir,
        },
      ],
    });

    await emitMcp({
      repoRoot,
      servers: mcp.map((s) => ({ id: `core/mcp:${s.name}`, name: s.name, server: s.server })),
    });

    await emitCodex({ repoRoot, configToml: "[replix]\nenabled=true\n" });

    await emitOpenCode({
      repoRoot,
      assets: assets.map((a) => ({ id: `core/${a.kind}:${a.fileName}`, kind: a.kind, fileName: a.fileName, srcPath: a.srcPath })),
    });

    const mcpOut = readFileSync(join(repoRoot, ".mcp.json"), "utf8");
    expect(mcpOut).toContain('"__generated_by": "replix"');

    const codexOut = readFileSync(join(repoRoot, ".codex", "config.toml"), "utf8");
    expect(codexOut.startsWith("# generated by replix\n")).toBeTrue();

    const skillOut = readFileSync(join(repoRoot, ".claude", "skills", "repo-status", "SKILL.md"), "utf8");
    expect(skillOut).toContain("Test skill fixture");

    const cmdOut = readFileSync(join(repoRoot, ".opencode", "command", "hello.md"), "utf8");
    expect(cmdOut).toContain("Test command fixture");

    const agentOut = readFileSync(join(repoRoot, ".opencode", "agent", "planner.md"), "utf8");
    expect(agentOut).toContain("Test agent fixture");

    const hookOut = readFileSync(join(repoRoot, ".opencode", "hooks", "pre-commit.sh"), "utf8");
    expect(hookOut).toContain("pre-commit fixture");

    const ruleOut = readFileSync(join(repoRoot, ".opencode", "rules", "style.md"), "utf8");
    expect(ruleOut).toContain("Test rule fixture");
  });
});
