import { describe, expect, it } from "bun:test";
import { mkdtempSync, readFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { loadLocalPack } from "../src/resolver/localPack";
import { loadPackMcpServers, loadPackOpenCodeCommands, packSkillByItemId } from "../src/resolver/coreItems";
import { emitClaude } from "../src/emitters/claude";
import { emitMcp } from "../src/emitters/mcp";
import { emitCodex } from "../src/emitters/codex";
import { emitOpenCode } from "../src/emitters/opencode";

const FIX = join(import.meta.dir, "..", "fixtures", "packs", "core");

describe("golden: core pack", () => {
  it("emits deterministic outputs", async () => {
    const repoRoot = mkdtempSync(join(tmpdir(), "nexus-golden-"));

    const pack = await loadLocalPack(FIX);
    const skill = packSkillByItemId(pack, "repo-status");
    const mcp = await loadPackMcpServers(FIX);
    const cmds = await loadPackOpenCodeCommands(FIX);

    await emitClaude({
      repoRoot,
      skills: [
        {
          id: "core:repo-status",
          itemId: skill.itemId,
          srcDir: skill.srcDir,
        },
      ],
    });

    await emitMcp({
      repoRoot,
      servers: mcp.map((s) => ({ id: `core/mcp:${s.name}`, name: s.name, server: s.server })),
    });

    await emitCodex({ repoRoot, configToml: "[nexus]\nenabled=true\n" });

    await emitOpenCode({
      repoRoot,
      commands: cmds.map((c) => ({ id: `core/commands:${c.fileName}`, fileName: c.fileName, srcPath: c.srcPath })),
    });

    const mcpOut = readFileSync(join(repoRoot, ".mcp.json"), "utf8");
    expect(mcpOut).toContain('"__generated_by": "nexus"');

    const codexOut = readFileSync(join(repoRoot, ".codex", "config.toml"), "utf8");
    expect(codexOut.startsWith("# generated by nexus\n")).toBeTrue();

    const skillOut = readFileSync(join(repoRoot, ".claude", "skills", "repo-status", "SKILL.md"), "utf8");
    expect(skillOut).toContain("Test skill fixture");

    const cmdOut = readFileSync(join(repoRoot, ".opencode", "commands", "hello.md"), "utf8");
    expect(cmdOut).toContain("Test command fixture");
  });
});
