import { describe, expect, it } from "bun:test";
import { mkdtempSync, writeFileSync, mkdirSync, readFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { $ } from "bun";

async function runCli(cwd: string): Promise<{ stdout: string; stderr: string; exitCode: number }> {
  const indexPath = join(import.meta.dir, "..", "src", "index.ts");
  try {
    const proc = await $`bun ${indexPath}`.cwd(cwd).quiet();
    return {
      stdout: proc.stdout?.toString() ?? "",
      stderr: proc.stderr?.toString() ?? "",
      exitCode: proc.exitCode ?? 0,
    };
  } catch (e: any) {
    return {
      stdout: e.stdout?.toString() ?? "",
      stderr: e.stderr?.toString() ?? "",
      exitCode: e.exitCode ?? 1,
    };
  }
}

describe("pack mode codex surface", () => {
  it("emits repo codex config without speculative default sections", async () => {
    const packRoot = mkdtempSync(join(tmpdir(), "replix-pack-codex-"));

    const skillDir = join(packRoot, "skills", "test-skill");
    mkdirSync(skillDir, { recursive: true });
    writeFileSync(join(skillDir, "SKILL.md"), "# Test Skill");

    const packJson = {
      id: "test",
      version: "1.0.0",
      imports: [],
      enable: {
        skills: ["test-skill"],
        mcp: [],
      },
    };
    writeFileSync(join(packRoot, "pack.json"), JSON.stringify(packJson, null, 2));

    const run = await runCli(packRoot);
    expect(run.exitCode).toBe(0);

    const codexPath = join(packRoot, ".codex", "config.toml");
    const raw = readFileSync(codexPath, "utf8");

    expect(raw.startsWith("# generated by replix\n")).toBeTrue();
    expect(raw).not.toContain("[skills]");
  });
});
