import { describe, expect, it } from "bun:test";
import { parseClientSpecSchema } from "../src/specSchema";

describe("client spec schema", () => {
  it("parses valid claude schema", () => {
    const parsed = parseClientSpecSchema({
      client: "claude",
      version: "2026-02-16",
      source: {
        docs: ["https://code.claude.com/docs/en/settings"],
        repo: "https://github.com/anthropics/claude-code",
      },
      artifacts: [
        {
          kind: "command",
          path: ".claude/commands/review.md",
          ownerMarker: "generated by replix",
          cleanup: "owned-only",
        },
      ],
    });

    expect(parsed.client).toBe("claude");
    expect(parsed.artifacts[0]?.kind).toBe("command");
  });

  it("rejects artifact path outside client roots", () => {
    expect(() =>
      parseClientSpecSchema({
        client: "codex",
        version: "1",
        source: {},
        artifacts: [
          {
            kind: "settings",
            path: ".claude/settings.json",
            cleanup: "owned-only",
          },
        ],
      }),
    ).toThrow(/outside allowed roots/);
  });

  it("rejects invalid artifact kind", () => {
    expect(() =>
      parseClientSpecSchema({
        client: "opencode",
        version: "1",
        source: {},
        artifacts: [
          {
            kind: "unknown",
            path: ".opencode/command/x.md",
            cleanup: "owned-only",
          },
        ],
      }),
    ).toThrow(/kind must be one of/);
  });
});
