import { mkdir, writeFile, readdir, stat, copyFile } from "node:fs/promises";
import { join } from "node:path";

export type ClaudeSkillInput = {
  id: string;
  itemId: string;
  srcDir: string;
};

export type EmitClaudeInput = {
  repoRoot: string;
  skills: ClaudeSkillInput[];
};

function shouldSkipEntry(name: string): boolean {
  return name === ".git" || name === ".hg" || name === ".svn";
}

async function copyDir(src: string, dst: string): Promise<void> {
  await mkdir(dst, { recursive: true });
  const entries = await readdir(src, { withFileTypes: true });
  for (const e of entries) {
    if (shouldSkipEntry(e.name)) continue;
    const s = join(src, e.name);
    const d = join(dst, e.name);
    if (e.isDirectory()) {
      await copyDir(s, d);
    } else if (e.isFile()) {
      await mkdir(join(d, ".."), { recursive: true });
      await copyFile(s, d);
    }
  }
}

export async function emitClaude(input: EmitClaudeInput): Promise<void> {
  const skillsRoot = join(input.repoRoot, ".claude", "skills");
  await mkdir(skillsRoot, { recursive: true });

  // ownership marker
  const markerPath = join(skillsRoot, ".replix-managed");
  await writeFile(markerPath, "generated by replix\n", "utf8");

  // emit enabled skills
  for (const skill of input.skills) {
    if (!skill.itemId) throw new Error(`skill missing itemId: ${skill.id}`);
    const outDir = join(skillsRoot, skill.itemId);

    // basic sanity: srcDir exists
    const st = await stat(skill.srcDir);
    if (!st.isDirectory()) throw new Error(`skill srcDir not a directory: ${skill.srcDir}`);

    await copyDir(skill.srcDir, outDir);
  }
}
