import { mkdir, writeFile, readdir, copyFile, stat } from "node:fs/promises";
import { join } from "node:path";
import type { ClaudeSkillInput } from "./claude";
import type { McpServerInput } from "./mcp";

export type EmitCodexInput = {
  repoRoot: string;
  configToml?: string;
  skills?: ClaudeSkillInput[];
  mcpServers?: McpServerInput[];
};

function shouldSkipEntry(name: string): boolean {
  return name === ".git" || name === ".hg" || name === ".svn";
}

async function copyDir(src: string, dst: string): Promise<void> {
  await mkdir(dst, { recursive: true });
  const entries = await readdir(src, { withFileTypes: true });
  for (const e of entries) {
    if (shouldSkipEntry(e.name)) continue;
    const s = join(src, e.name);
    const d = join(dst, e.name);
    if (e.isDirectory()) {
      await copyDir(s, d);
    } else if (e.isFile()) {
      await mkdir(join(d, ".."), { recursive: true });
      await copyFile(s, d);
    }
  }
}

function quoteToml(v: string): string {
  return JSON.stringify(v);
}

function renderCodexMcpToml(servers: McpServerInput[]): string {
  const lines: string[] = [];
  for (const s of servers) {
    lines.push(`[mcp_servers.${s.name}]`);
    lines.push(`command = ${quoteToml(s.server.command)}`);
    if ((s.server.args ?? []).length > 0) {
      lines.push(`args = [${(s.server.args ?? []).map(quoteToml).join(", ")}]`);
    }
    if (s.server.env && Object.keys(s.server.env).length > 0) {
      const envEntries = Object.entries(s.server.env).map(([k, v]) => `${k} = ${quoteToml(v)}`).join(", ");
      lines.push(`env = { ${envEntries} }`);
    }
    lines.push("");
  }
  return lines.join("\n").trim() + (lines.length ? "\n" : "");
}

export async function emitCodex(input: EmitCodexInput): Promise<void> {
  const dir = join(input.repoRoot, ".codex");
  await mkdir(dir, { recursive: true });

  const outPath = join(dir, "config.toml");
  const header = "# generated by nexus\n";
  const mcpToml = renderCodexMcpToml(input.mcpServers ?? []);
  const extraToml = typeof input.configToml === "string" ? (input.configToml.endsWith("\n") ? input.configToml : input.configToml + "\n") : "";
  await writeFile(outPath, header + mcpToml + extraToml, "utf8");

  for (const skill of input.skills ?? []) {
    if (!skill.itemId) throw new Error(`codex skill missing itemId: ${skill.id}`);
    const st = await stat(skill.srcDir);
    if (!st.isDirectory()) throw new Error(`codex skill srcDir not a directory: ${skill.srcDir}`);

    // Codex docs define skill discovery under .agents/skills (repo + user/admin/system scopes).
    await copyDir(skill.srcDir, join(input.repoRoot, ".agents", "skills", skill.itemId));
  }
}
