import { mkdir, writeFile } from "node:fs/promises";
import { join } from "node:path";

export type EmitCodexInput = {
  repoRoot: string;
  configToml: string;
};

export async function emitCodex(input: EmitCodexInput): Promise<void> {
  const dir = join(input.repoRoot, ".codex");
  await mkdir(dir, { recursive: true });

  const outPath = join(dir, "config.toml");
  const header = "# generated by nexus\n";
  const body = input.configToml.endsWith("\n") ? input.configToml : input.configToml + "\n";
  await writeFile(outPath, header + body, "utf8");
}
