import { mkdir, writeFile, copyFile } from "node:fs/promises";
import { join } from "node:path";

export type OpenCodeCommandInput = {
  id: string;
  fileName: string;
  srcPath: string;
};

export type EmitOpenCodeInput = {
  repoRoot: string;
  commands: OpenCodeCommandInput[];
};

export async function emitOpenCode(input: EmitOpenCodeInput): Promise<void> {
  const root = join(input.repoRoot, ".opencode");
  const cmdsDir = join(root, "commands");
  await mkdir(cmdsDir, { recursive: true });

  const marker = join(root, ".nexus-managed");
  await writeFile(marker, "generated by nexus\n", "utf8");

  for (const cmd of input.commands) {
    if (!cmd.fileName) throw new Error(`command missing fileName: ${cmd.id}`);
    const out = join(cmdsDir, cmd.fileName);
    await copyFile(cmd.srcPath, out);
  }
}
