import { copyFile, mkdir, writeFile, readdir, stat } from "node:fs/promises";
import { join } from "node:path";
import type { ClaudeSkillInput } from "./claude";
import type { McpServerInput } from "./mcp";

// Upstream opencode uses singular dirs: .opencode/command and .opencode/agent.
// We keep hooks/rules as Nexus extensions for now.
export type OpenCodeAssetKind = "command" | "agent" | "hooks" | "rules";

export type OpenCodeAssetInput = {
  id: string;
  kind: OpenCodeAssetKind;
  fileName: string;
  srcPath: string;
};

export type EmitOpenCodeInput = {
  repoRoot: string;
  assets?: OpenCodeAssetInput[];
  skills?: ClaudeSkillInput[];
  mcpServers?: McpServerInput[];
};

function shouldSkipEntry(name: string): boolean {
  return name === ".git" || name === ".hg" || name === ".svn";
}

async function copyDir(src: string, dst: string): Promise<void> {
  await mkdir(dst, { recursive: true });
  const entries = await readdir(src, { withFileTypes: true });
  for (const e of entries) {
    if (shouldSkipEntry(e.name)) continue;
    const s = join(src, e.name);
    const d = join(dst, e.name);
    if (e.isDirectory()) {
      await copyDir(s, d);
    } else if (e.isFile()) {
      await mkdir(join(d, ".."), { recursive: true });
      await copyFile(s, d);
    }
  }
}

function toOpenCodeMcpConfig(servers: McpServerInput[]): Record<string, unknown> {
  const mcp: Record<string, unknown> = {};
  for (const s of servers) {
    const command = [s.server.command, ...(s.server.args ?? [])];
    mcp[s.name] = {
      type: "local",
      command,
      enabled: true,
      ...(s.server.env ? { environment: s.server.env } : {}),
    };
  }
  return {
    $schema: "https://opencode.ai/config.json",
    mcp,
  };
}

export async function emitOpenCode(input: EmitOpenCodeInput): Promise<void> {
  const root = join(input.repoRoot, ".opencode");
  await mkdir(root, { recursive: true });

  const marker = join(root, ".nexus-managed");
  await writeFile(marker, "generated by nexus\n", "utf8");

  for (const asset of input.assets ?? []) {
    if (!asset.fileName) throw new Error(`opencode asset missing fileName: ${asset.id}`);
    const outDir = join(root, asset.kind);
    await mkdir(outDir, { recursive: true });
    const out = join(outDir, asset.fileName);
    await copyFile(asset.srcPath, out);
  }

  for (const skill of input.skills ?? []) {
    if (!skill.itemId) throw new Error(`opencode skill missing itemId: ${skill.id}`);
    const st = await stat(skill.srcDir);
    if (!st.isDirectory()) throw new Error(`opencode skill srcDir not a directory: ${skill.srcDir}`);
    await copyDir(skill.srcDir, join(root, "skills", skill.itemId));
  }

  if ((input.mcpServers ?? []).length > 0) {
    const configPath = join(input.repoRoot, "opencode.json");
    const payload = toOpenCodeMcpConfig(input.mcpServers ?? []);
    await writeFile(configPath, JSON.stringify(payload, null, 2) + "\n", "utf8");
  }
}
