import { copyFile, mkdir, writeFile } from "node:fs/promises";
import { join } from "node:path";

// Upstream opencode uses singular dirs: .opencode/command and .opencode/agent.
// We keep hooks/rules as Nexus extensions for now.
export type OpenCodeAssetKind = "command" | "agent" | "hooks" | "rules";

export type OpenCodeAssetInput = {
  id: string;
  kind: OpenCodeAssetKind;
  fileName: string;
  srcPath: string;
};

export type EmitOpenCodeInput = {
  repoRoot: string;
  assets: OpenCodeAssetInput[];
};

export async function emitOpenCode(input: EmitOpenCodeInput): Promise<void> {
  const root = join(input.repoRoot, ".opencode");
  await mkdir(root, { recursive: true });

  const marker = join(root, ".nexus-managed");
  await writeFile(marker, "generated by nexus\n", "utf8");

  for (const asset of input.assets) {
    if (!asset.fileName) throw new Error(`opencode asset missing fileName: ${asset.id}`);
    const outDir = join(root, asset.kind);
    await mkdir(outDir, { recursive: true });
    const out = join(outDir, asset.fileName);
    await copyFile(asset.srcPath, out);
  }
}
