import { readdir, rm, stat, readFile } from "node:fs/promises";
import { join } from "node:path";

export type CleanupInput = {
  repoRoot: string;
  /** Absolute paths that should exist after emit. */
  desiredPaths: string[];
};

async function pathExists(p: string): Promise<boolean> {
  try {
    await stat(p);
    return true;
  } catch (e: any) {
    if (e?.code === "ENOENT") return false;
    throw e;
  }
}

async function fileContains(p: string, needle: string): Promise<boolean> {
  try {
    const raw = await readFile(p, "utf8");
    return raw.includes(needle);
  } catch (e: any) {
    if (e?.code === "ENOENT") return false;
    throw e;
  }
}

async function removeStaleChildren(dir: string, desiredAbs: Set<string>): Promise<void> {
  if (!(await pathExists(dir))) return;
  const entries = await readdir(dir, { withFileTypes: true });

  for (const e of entries) {
    const child = join(dir, e.name);
    // Keep anything explicitly desired or a parent of desired.
    let keep = false;
    for (const d of desiredAbs) {
      if (d === child) keep = true;
      else if (d.startsWith(child + "/")) keep = true;
      else if (child.startsWith(d + "/")) keep = true;
      if (keep) break;
    }
    if (keep) continue;

    await rm(child, { recursive: true, force: true });
  }
}

export async function cleanupOwnedOnly(input: CleanupInput): Promise<void> {
  const desiredAbs = new Set(input.desiredPaths);

  // Claude owned marker: .claude/skills/.nexus-managed
  const claudeSkillsRoot = join(input.repoRoot, ".claude", "skills");
  const claudeMarker = join(claudeSkillsRoot, ".nexus-managed");
  if (await pathExists(claudeMarker)) {
    await removeStaleChildren(claudeSkillsRoot, desiredAbs);
  }

  // OpenCode owned marker: .opencode/.nexus-managed
  const ocRoot = join(input.repoRoot, ".opencode");
  const ocMarker = join(ocRoot, ".nexus-managed");
  if (await pathExists(ocMarker)) {
    await removeStaleChildren(ocRoot, desiredAbs);
  }

  // MCP owned marker: .mcp.json contains __generated_by:nexus
  const mcpPath = join(input.repoRoot, ".mcp.json");
  if (await fileContains(mcpPath, '"__generated_by": "nexus"')) {
    if (!desiredAbs.has(mcpPath)) await rm(mcpPath, { force: true });
  }

  // Codex owned marker: .codex/config.toml contains header
  const codexPath = join(input.repoRoot, ".codex", "config.toml");
  if (await fileContains(codexPath, "# generated by nexus")) {
    if (!desiredAbs.has(codexPath)) await rm(codexPath, { force: true });
  }
}

export async function cleanupFull(repoRoot: string): Promise<void> {
  await rm(join(repoRoot, ".claude", "skills"), { recursive: true, force: true });
  await rm(join(repoRoot, ".mcp.json"), { force: true });
  await rm(join(repoRoot, ".codex", "config.toml"), { force: true });
  await rm(join(repoRoot, ".opencode", "commands"), { recursive: true, force: true });
  await rm(join(repoRoot, ".opencode", ".nexus-managed"), { force: true });
}
